services:
  - type: web
    name: gps-danger-zone-tracker
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: python start.py
    envVars:
      - key: PYTHON_VERSION
        value: 3.10.0
    healthCheckPath: /api/status
